import type { Category, QuickLink } from "./types";

export const categories: Category[] = [
  { name: "Beauty & Salon", icon: "💇", keywords: ["Beauty Parlour", "Salon", "Makeup Artist"] },
  { name: "Coaching & Tuition", icon: "📚", keywords: ["Coaching", "Tutor", "Competitive Exams"] },
  { name: "Doctor & Clinic", icon: "🩺", keywords: ["Doctor", "Clinic", "Specialist"] },
  { name: "Hospital & Healthcare", icon: "🏥", keywords: ["Hospital", "Healthcare", "Nursing Home"] },
  { name: "Restaurant & Food", icon: "🍽️", keywords: ["Restaurant", "North Indian", "Fast Food"] },
  { name: "Cafe & Bakery", icon: "☕", keywords: ["Cafe", "Bakery", "Coffee"] },
  { name: "Real Estate", icon: "🏠", keywords: ["Property Dealer", "Buy Property", "Rent"] },
  { name: "Architect & Interior", icon: "📐", keywords: ["Architect", "Interior Designer", "3D Design"] },
  { name: "Construction & Contractor", icon: "🏗️", keywords: ["Contractor", "Civil Work", "Construction"] },
  { name: "Home Services", icon: "🛠️", keywords: ["Electrician", "Plumber", "Carpenter"] },
  { name: "Repair & Maintenance", icon: "🔧", keywords: ["AC Repair", "Fridge Repair", "Washing Machine Repair"] },
  { name: "Automobile", icon: "🚗", keywords: ["Car Repair", "Bike Repair", "Car Service"] },
  { name: "Mobile & Computer", icon: "📱", keywords: ["Mobile Repair", "Laptop Repair", "Computer Repair"] },
  { name: "Electrical & Electronics", icon: "🔌", keywords: ["Electronics", "Electrical Shop", "Inverter"] },
  { name: "Security & CCTV", icon: "📹", keywords: ["CCTV", "Security", "Alarm"] },
  { name: "Furniture & Home Decor", icon: "🛋️", keywords: ["Furniture", "Home Decor", "Modular Furniture"] },
  { name: "Clothing & Fashion", icon: "👗", keywords: ["Boutique", "Clothing", "Fashion"] },
  { name: "Grocery & Supermarket", icon: "🛒", keywords: ["Grocery", "Supermarket", "Kirana"] },
  { name: "Pharmacy & Medical", icon: "💊", keywords: ["Pharmacy", "Medical Store", "Medicine"] },
  { name: "Fitness & Wellness", icon: "🏋️", keywords: ["Gym", "Yoga", "Fitness"] },
  { name: "Travel & Tourism", icon: "✈️", keywords: ["Travel Agency", "Tour", "Holiday"] },
  { name: "Hotel & Accommodation", icon: "🏨", keywords: ["Hotel", "Guest House", "Rooms"] },
  { name: "Photography & Videography", icon: "📸", keywords: ["Photographer", "Wedding Photography", "Videographer"] },
  { name: "Event & Wedding Services", icon: "💍", keywords: ["Wedding Planner", "Decorator", "Event Planner"] },
];

export const allCategoryNames = [
  "Beauty & Salon",
  "Coaching & Tuition",
  "School & Education",
  "College & University",
  "Training & Skill Development",
  "Doctor & Clinic",
  "Hospital & Healthcare",
  "Pharmacy & Medical",
  "Diagnostic & Pathology",
  "Dental Care",
  "Fitness & Wellness",
  "Restaurant & Food",
  "Cafe & Bakery",
  "Sweet & Namkeen",
  "Caterers",
  "Hotel & Accommodation",
  "Travel & Tourism",
  "Real Estate",
  "Architect & Interior",
  "Construction & Contractor",
  "Building Material",
  "Home Services",
  "Repair & Maintenance",
  "Furniture & Home Decor",
  "Electrical & Electronics",
  "Hardware & Sanitary",
  "Tiles, Marble & Flooring",
  "Paint & Wallpaper",
  "Aluminium, Glass & UPVC",
  "Fabrication & Welding",
  "Solar & Energy",
  "Security & CCTV",
  "Automobile",
  "Rental & Leasing",
  "Driving School",
  "Transport & Logistics",
  "Courier & Delivery",
  "Clothing & Fashion",
  "Boutique & Tailoring",
  "Jewellery & Accessories",
  "Footwear & Bags",
  "Cosmetics & Beauty Products",
  "Grocery & Supermarket",
  "Mobile & Computer",
  "IT & Software Services",
  "Printing & Advertising",
  "Photography & Videography",
  "Event & Wedding Services",
  "Entertainment & Recreation",
  "Sports & Games",
  "Kids & Childcare",
  "Pet & Veterinary",
  "Agriculture & Farming",
  "Nursery & Landscaping",
  "Manufacturing",
  "Wholesale & Distribution",
  "Dealer & Supplier",
  "Industrial Services",
  "Machinery & Equipment",
  "Business & Management Consulting",
  "CA & Tax Services",
  "Legal Services",
  "Finance & Loan",
  "Insurance",
  "Banking & ATM",
  "Digital Marketing",
  "Graphic & Creative Services",
  "Recruitment & Manpower",
  "Cleaning Services",
  "Domestic Help",
  "Laundry & Dry Cleaning",
  "Property Services",
  "Government & Public Services",
  "NGO & Social Services",
  "Religious & Community Services",
  "Professional Services",
  "Security Services",
  "Party & Event Rental",
  "Repair, Installation & Maintenance",
  "Other Services",
];

export const popularSearches: QuickLink[] = [
  "Beauty Parlour",
  "Restaurant",
  "Doctor",
  "Gym",
  "Coaching",
  "Salon",
  "Electrician",
  "Plumber",
  "Car Repair",
  "Property Dealer",
  "Cafe",
  "Hotel",
  "Photographer",
  "Tutor",
  "Interior Designer",
].map((label) => ({
  label,
  query: label,
}));

export const popularServices: QuickLink[] = [
  "Electrician",
  "Plumber",
  "AC Repair",
  "Beauty Parlour",
  "Home Cleaning",
  "Car Wash",
  "Makeup Artist",
  "Home Tutor",
  "Dentist",
  "Photographer",
  "Interior Designer",
  "Property Dealer",
  "Laptop Repair",
  "Mobile Repair",
].map((label) => ({
  label,
  query: label,
}));

export const popularLocations = [
  "Lucknow",
  "Delhi",
  "Mumbai",
  "Bangalore",
  "Hyderabad",
  "Pune",
  "Jaipur",
  "Kanpur",
  "Noida",
  "Ghaziabad",
];